#!/bin/sh
# Sample simulator to Dakota system call script
# See Advanced Simulation Code Interfaces chapter in Users Manual

# $1 is params.in FROM Dakota
# $2 is results.out returned to Dakota

# --------------
# PRE-PROCESSING
# --------------
# Incorporate the parameters from DAKOTA into the template, writing ros.in
# Use the following line if SNL's APREPRO utility is used instead of DPrePro.
# ../aprepro -c '*' -q --nowarning ros.template ros.in


dprepro $1 U.template U.in

# --------
# ANALYSIS
# --------

pwd
cp -r ../casebase/* .
cp U.in 0/U

blockMesh > log.blockmesh
icoFoam > log.icofoam
probeLocations -latestTime > log.probes

# ---------------
# POST-PROCESSING
# ---------------


#touch results.out
#cp ../casebase/results.out .

tail -n 1 postProcessing/probes/0.5/p | cut -c 15-  > tmp.txt
mv tmp.txt $2